services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./exams-app:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: rebase-labs
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres-data:
